#!/command/with-contenv bash
# shellcheck shell=bash disable=SC1091,SC2015,SC2164,SC2068,SC2145,SC2154

source /scripts/common

#---------------------------------------------------------------------------------------------
# This repository, docker container, and accompanying scripts and documentation is
# Copyright (C) 2022-2024, Ramon F. Kolb (kx1t) and contributors
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.
#
# Radar1090 is an ADS-B RADAR Feed Service
# Copyright (C) 2023 by Michael J. Tubby B.Sc. MIET G8TIC mik@tubby.org All Rights Reserved.
# No license to the "radar" binary and its source code is implied; contact the author for information.
#---------------------------------------------------------------------------------------------

# Run radar1090 as a long term service

"${s6wrap[@]}" echo "starting as a service..."

if [[ -z "${RADAR1090_KEY}" ]]; then
	"${s6wrap[@]}" echo "FATAL: RADAR1090_KEY not set. Halting operation."
	exec sleep infinity
fi

BEASTHOST="${BEASTHOST:-ultrafeeder}"

if ! nc -z "${BEASTHOST}" 30005 >/dev/null 2>&1; then
    "${s6wrap[@]}" echo "INFO: Waiting for BEASTHOST (${BEASTHOST}) to come online"
    while ! nc -z "${BEASTHOST}" 30005 >/dev/null 2>&1; do
        sleep 1
    done
    "${s6wrap[@]}" echo "INFO: BEASTHOST (${BEASTHOST}) is now online"
fi

RADAR_BIN=(stdbuf -oL /usr/sbin/radar)

RADAR_CMD=()
RADAR_CMD+=("-k ${RADAR1090_KEY}")
if (( $(bc -l <<< "$(awk -F- '{print $1}' < /.CONTAINER_VERSION) > 2.00") == 1 )); then
  RADAR_CMD+=("${RADARSERVER:+-h }${RADARSERVER}")
else
  RADAR_CMD+=("-h ${RADARSERVER:-adsb-in.1090mhz.uk}")
fi
RADAR_CMD+=("${HMAC_KEY:+-p }${HMAC_KEY}")
RADAR_CMD+=("-l ${BEASTHOST}")
RADAR_CMD+=("-f")

# Make sure logfile exists and is writable with UID "radar".
# Probably not necessary as the redirect runs as `root`, but better be safe than sorry
touch /var/log/radar1090
chmod a+w /var/log/radar1090

"${s6wrap[@]}" echo "invoking: ${RADAR_BIN[@]} ${RADAR_CMD[@]}"
exec ${RADAR_BIN[@]} ${RADAR_CMD[@]} >> /var/log/radar1090
