#!/command/with-contenv bash
# shellcheck shell=bash disable=SC1091,SC2015,SC2164,SC2068,SC2145

source /scripts/common
s6wrap=(s6wrap --quiet --timestamps --prepend="$(basename "$0")")

#---------------------------------------------------------------------------------------------
# This repository, docker container, and accompanying scripts and documentation is
# Copyright (C) 2022-2023, Ramon F. Kolb (kx1t)
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.
#
# Radar1090 is an ADS-B RADAR Feed Service
# Copyright (C) 2023 by Michael J. Tubby B.Sc. MIET G8TIC mik@tubby.org All Rights Reserved.
# No license to the "radar" binary and its source code is implied; contact the author for information.
#---------------------------------------------------------------------------------------------

# Run radar1090 as a long term service

"${s6wrap[@]}" --args echo "Starting radar 1090 as a service..."

function valid_ip()
{
    local  ip=$1
    local  stat=1

    if [[ $ip =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
        OIFS=$IFS
        IFS='.'
        ip=($ip)
        IFS=$OIFS
        [[ ${ip[0]} -le 255 && ${ip[1]} -le 255 \
            && ${ip[2]} -le 255 && ${ip[3]} -le 255 ]]
        stat=$?
    fi
    return $stat
}

if [[ -z "${RADAR1090_KEY}" ]]; then
	"${s6wrap[@]}" --args echo "FATAL: RADAR1090_KEY not set. Halting operation."
	exec sleep infinity
fi

beast_host="${BEASTHOST:-ultrafeeder}"
if ! valid_ip "$beast_host"; then
	beast_host="$(dig "$beast_host" | awk '{if ($1 == "'"$beast_host"'.") print $5}')"
	if [[ -z "$beast_host" ]]; then
		"${s6wrap[@]}" --args echo "FATAL: BEASTHOST (\"$BEASTHOST\") must be a resolvable domain/hostname or an IP address. Halting operation."
		exec sleep infinity
	fi
fi

RADAR_BIN=(/usr/sbin/radar)

RADAR_CMD=("-b")
RADAR_CMD+=("-k ${RADAR1090_KEY}")
RADAR_CMD+=("-h ${RADARSERVER:-adsb-in.1090mhz.uk}")
RADAR_CMD+=("-p ${RADARPORT:-2227}")
RADAR_CMD+=("-l ${beast_host}")
chk_enabled "$VERBOSE" && RADAR_CMD+=("-s") || true

"${s6wrap[@]}" --args echo "invoking: ${RADAR_BIN[@]} ${RADAR_CMD[@]}"
"${s6wrap[@]}" --args ${RADAR_BIN[@]} ${RADAR_CMD[@]}
